// SPDX-FileCopyrightText: 2024 Christina Sørensen
// SPDX-License-Identifier: EUPL-1.2
//
// SPDX-FileCopyrightText: 2023-2024 Christina Sørensen, eza contributors
// SPDX-FileCopyrightText: 2014 Benjamin Sago
// SPDX-License-Identifier: MIT

// spell:disable

use nu_ansi_term::Style;
use phf::{Map, phf_map};

use crate::fs::File;

#[non_exhaustive]
struct Icons;

/* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— */

#[rustfmt::skip]
impl Icons {
    const AUDIO           : char = '\u{f001}'  ; // 
    const BINARY          : char = '\u{eae8}'  ; // 
    const BOOK            : char = '\u{e28b}'  ; // 
    const CALENDAR        : char = '\u{eab0}'  ; // 
    const CACHE           : char = '\u{f49b}'  ; // 
    const CAD             : char = '\u{f0eeb}' ; // 󰻫
    const CLOCK           : char = '\u{f43a}'  ; // 
    const COMPRESSED      : char = '\u{f410}'  ; // 
    const CONFIG          : char = '\u{f107b}' ; // 󱁻
    const CSS3            : char = '\u{e749}'  ; // 
    const DATABASE        : char = '\u{f1c0}'  ; // 
    const DIFF            : char = '\u{f440}'  ; // 
    const DISK_IMAGE      : char = '\u{e271}'  ; // 
    const DOCKER          : char = '\u{e650}'  ; // 
    const DOCUMENT        : char = '\u{f1c2}'  ; // 
    const DOWNLOAD        : char = '\u{f01da}' ; // 󰇚
    const EDA_SCH         : char = '\u{f0b45}' ; // 󰭅
    const EDA_PCB         : char = '\u{eabe}'  ; // 
    const EMACS           : char = '\u{e632}'  ; // 
    const ESLINT          : char = '\u{e655}'  ; // 
    const FILE            : char = '\u{f15b}'  ; // 
    const FILE_3D         : char = '\u{f01a7}' ; // 󰆧
    const FOLDER          : char = '\u{e5ff}'  ; // 
    const FOLDER_BUILD    : char = '\u{f19fc}' ; // 󱧼
    const FOLDER_CONFIG   : char = '\u{e5fc}'  ; // 
    const FOLDER_EXERCISM : char = '\u{ebe5}'  ; // 
    const FOLDER_GIT      : char = '\u{e5fb}'  ; // 
    const FOLDER_GITHUB   : char = '\u{e5fd}'  ; // 
    const FOLDER_HIDDEN   : char = '\u{f179e}' ; // 󱞞
    const FOLDER_KEY      : char = '\u{f08ac}' ; // 󰢬
    const FOLDER_NPM      : char = '\u{e5fa}'  ; // 
    const FOLDER_OCAML    : char = '\u{e67a}'  ; // 
    const FOLDER_OPEN     : char = '\u{f115}'  ; // 
    const FILE_UNKNOW     : char = '\u{f086f}' ; // 󰡯
    const FONT            : char = '\u{f031}'  ; // 
    const FREECAD         : char = '\u{f336}'  ; // 
    const GIMP            : char = '\u{f338}'  ; // 
    const GIST_SECRET     : char = '\u{eafa}'  ; // 
    const GIT             : char = '\u{f02a2}' ; // 󰊢
    const GODOT           : char = '\u{e65f}'  ; // 
    const GRADLE          : char = '\u{e660}'  ; // 
    const GRAPH           : char = '\u{f1049}' ; // 󱁉
    const GRAPHQL         : char = '\u{e662}'  ; // 
    const GRUNT           : char = '\u{e611}'  ; // 
    const GTK             : char = '\u{f362}'  ; // 
    const GULP            : char = '\u{e610}'  ; // 
    const HTML5           : char = '\u{f13b}'  ; // 
    const IMAGE           : char = '\u{f1c5}'  ; // 
    const INFO            : char = '\u{f129}'  ; // 
    const INTELLIJ        : char = '\u{e7b5}'  ; // 
    const JSON            : char = '\u{e60b}'  ; // 
    const KEY             : char = '\u{eb11}'  ; // 
    const KDENLIVE        : char = '\u{f33c}'  ; // 
    const KEYPASS         : char = '\u{f23e}'  ; // 
    const KICAD           : char = '\u{f34c}'  ; // 
    const KRITA           : char = '\u{f33d}'  ; // 
    const LANG_ARDUINO    : char = '\u{f34b}'  ; // 
    const LANG_ASSEMBLY   : char = '\u{e637}'  ; // 
    const LANG_C          : char = '\u{e61e}'  ; // 
    const LANG_CPP        : char = '\u{e61d}'  ; // 
    const LANG_CSHARP     : char = '\u{f031b}' ; // 󰌛
    const LANG_D          : char = '\u{e7af}'  ; // 
    const LANG_ELIXIR     : char = '\u{e62d}'  ; // 
    const LANG_FENNEL     : char = '\u{e6af}'  ; // 
    const LANG_FORTRAN    : char = '\u{f121a}' ; // 󱈚
    const LANG_FSHARP     : char = '\u{e7a7}'  ; // 
    const LANG_GLEAM      : char = '\u{f09a5}' ; // 󰦥
    const LANG_GO         : char = '\u{e65e}'  ; // 
    const LANG_GROOVY     : char = '\u{e775}'  ; // 
    const LANG_HASKELL    : char = '\u{e777}'  ; // 
    const LANG_HDL        : char = '\u{f035b}' ; // 󰍛
    const LANG_HOLYC      : char = '\u{f00a2}' ; // 󰂢
    const LANG_JAVA       : char = '\u{e256}'  ; // 
    const LANG_JAVASCRIPT : char = '\u{e74e}'  ; // 
    const LANG_KOTLIN     : char = '\u{e634}'  ; // 
    const LANG_LUA        : char = '\u{e620}'  ; // 
    const LANG_NIM        : char = '\u{e677}'  ; // 
    const LANG_OCAML      : char = '\u{e67a}'  ; // 
    const LANG_PERL       : char = '\u{e67e}'  ; // 
    const LANG_PHP        : char = '\u{e73d}'  ; // 
    const LANG_PYTHON     : char = '\u{e606}'  ; // 
    const LANG_R          : char = '\u{e68a}'  ; // 
    const LANG_RUBY       : char = '\u{e739}'  ; // 
    const LANG_RUBYRAILS  : char = '\u{e73b}'  ; // 
    const LANG_RUST       : char = '\u{e68b}'  ; // 
    const LANG_SASS       : char = '\u{e603}'  ; // 
    const LANG_SCHEME     : char = '\u{e6b1}'  ; // 
    const LANG_STYLUS     : char = '\u{e600}'  ; // 
    const LANG_TEX        : char = '\u{e69b}'  ; // 
    const LANG_TYPESCRIPT : char = '\u{e628}'  ; // 
    const LANG_V          : char = '\u{e6ac}'  ; // 
    const LIBRARY         : char = '\u{eb9c}'  ; // 
    const LICENSE         : char = '\u{f02d}'  ; // 
    const LOCK            : char = '\u{f023}'  ; // 
    const LOG             : char = '\u{f18d}'  ; // 
    const MAKE            : char = '\u{e673}'  ; // 
    const MARKDOWN        : char = '\u{f48a}'  ; // 
    const MUSTACHE        : char = '\u{e60f}'  ; // 
    const NEWS            : char = '\u{f1ea}'  ; // 
    const NODEJS          : char = '\u{e718}'  ; // 
    const NOTEBOOK        : char = '\u{e678}'  ; // 
    const NPM             : char = '\u{e71e}'  ; // 
    const OS_ANDROID      : char = '\u{e70e}'  ; // 
    const OS_APPLE        : char = '\u{f179}'  ; // 
    const OS_LINUX        : char = '\u{f17c}'  ; // 
    const OS_WINDOWS      : char = '\u{f17a}'  ; // 
    const OS_WINDOWS_CMD  : char = '\u{ebc4}'  ; // 
    const PLAYLIST        : char = '\u{f0cb9}' ; // 󰲹
    const POWERSHELL      : char = '\u{ebc7}'  ; // 
    const PRIVATE_KEY     : char = '\u{f0306}' ; // 󰌆
    const PUBLIC_KEY      : char = '\u{f0dd6}' ; // 󰷖
    const QT              : char = '\u{f375}'  ; // 
    const RAZOR           : char = '\u{f1fa}'  ; // 
    const REACT           : char = '\u{e7ba}'  ; // 
    const README          : char = '\u{f00ba}' ; // 󰂺
    const SHEET           : char = '\u{f1c3}'  ; // 
    const SHELL           : char = '\u{f1183}' ; // 󱆃
    const SHELL_CMD       : char = '\u{f489}'  ; // 
    const SHIELD_CHECK    : char = '\u{f0565}' ; // 󰕥
    const SHIELD_KEY      : char = '\u{f0bc4}' ; // 󰯄
    const SHIELD_LOCK     : char = '\u{f099d}' ; // 󰦝
    const SIGNED_FILE     : char = '\u{f19c3}' ; // 󱧃
    const SLIDE           : char = '\u{f1c4}'  ; // 
    const SQLITE          : char = '\u{e7c4}'  ; // 
    const SUBLIME         : char = '\u{e7aa}'  ; // 
    const SUBTITLE        : char = '\u{f0a16}' ; // 󰨖
    const TCL             : char = '\u{f06d3}' ; // 󰛓
    const TERRAFORM       : char = '\u{f1062}' ; // 󱁢
    const TEXT            : char = '\u{f15c}'  ; // 
    const TODO            : char = '\u{f0ae}'  ; // 
    const TYPST           : char = '\u{f37f}'  ; // 
    const TMUX            : char = '\u{ebc8}'  ; // 
    const TOML            : char = '\u{e6b2}'  ; // 
    const TRANSLATION     : char = '\u{f05ca}' ; // 󰗊
    const UNITY           : char = '\u{e721}'  ; // 
    const VECTOR          : char = '\u{f0559}' ; // 󰕙
    const VIDEO           : char = '\u{f03d}'  ; // 
    const VIM             : char = '\u{e7c5}'  ; // 
    const WRENCH          : char = '\u{f0ad}'  ; // 
    const XML             : char = '\u{f05c0}' ; // 󰗀
    const XORG            : char = '\u{f369}'  ; // 
    const YAML            : char = '\u{e8eb}'  ; // 
    const YARN            : char = '\u{e6a7}'  ; // 
}

/* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— */

/// Mapping from full filenames to directory icon. This mapping should contain
/// all the directories that have a custom icon.
const DIRECTORY_ICONS: Map<&'static str, char> = phf_map! {
    "Mail"          => '\u{f01f0}'            , // 󰇰
    "Contacts"      => '\u{f024c}'            , // 󰉌
    "Downloads"     => '\u{f024d}'            , // 󰉍
    "Pictures"      => '\u{f024f}'            , // 󰉏
    "Favorites"     => '\u{f069d}'            , // 󰚝
    ".ssh"          => Icons::FOLDER_KEY      , // 󰢬
    "pam.d"         => Icons::FOLDER_KEY      , // 󰢬
    "ssh"           => Icons::FOLDER_KEY      , // 󰢬
    "sudoers.d"     => Icons::FOLDER_KEY      , // 󰢬
    "src"           => '\u{f08de}'            , // 󰣞
    "Documents"     => '\u{f0c82}'            , // 󰲂
    "Movies"        => '\u{f0fce}'            , // 󰿎
    "home"          => '\u{f10b5}'            , // 󱂵
    "Music"         => '\u{f1359}'            , // 󱍙
    "hidden"        => Icons::FOLDER_HIDDEN   , // 󱞞
    "build"         => Icons::FOLDER_BUILD    , // 󱧼
    ".npm"          => Icons::FOLDER_NPM      , // 
    "node_modules"  => Icons::FOLDER_NPM      , // 
    "npm_cache"     => Icons::FOLDER_NPM      , // 
    ".git"          => Icons::FOLDER_GIT      , // 
    ".config"       => Icons::FOLDER_CONFIG   , // 
    "config"        => Icons::FOLDER_CONFIG   , // 
    "cron.d"        => Icons::FOLDER_CONFIG   , // 
    "cron.daily"    => Icons::FOLDER_CONFIG   , // 
    "cron.hourly"   => Icons::FOLDER_CONFIG   , // 
    "cron.minutely" => Icons::FOLDER_CONFIG   , // 
    "cron.monthly"  => Icons::FOLDER_CONFIG   , // 
    "cron.weekly"   => Icons::FOLDER_CONFIG   , // 
    "etc"           => Icons::FOLDER_CONFIG   , // 
    "include"       => Icons::FOLDER_CONFIG   , // 
    "pacman.d"      => Icons::FOLDER_CONFIG   , // 
    "xbps.d"        => Icons::FOLDER_CONFIG   , // 
    "xorg.conf.d"   => Icons::FOLDER_CONFIG   , // 
    ".github"       => Icons::FOLDER_GITHUB   , // 
    ".opam"         => Icons::FOLDER_OCAML    , // 
    "cabal"         => Icons::LANG_HASKELL    , // 
    ".exercism"     => Icons::FOLDER_EXERCISM , // 
    "Videos"        => '\u{f03d}'             , // 
    "Desktop"       => '\u{f108}'             , // 
    ".Trash"        => '\u{f1f8}'             , // 
};

/* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— */

/// Mapping from full filenames to file icon. This mapping should also contain
/// all the "dot" files that have a custom icon.
const FILENAME_ICONS: Map<&'static str, char> = phf_map! {
    "Vagrantfile"                => '\u{2371}'             , // ⍱
    "favicon.ico"                => '\u{e623}'             , // 
    ".editorconfig"              => '\u{e652}'             , // 
    "Jenkinsfile"                => '\u{e66e}'             , // 
    "pom.xml"                    => '\u{e674}'             , // 
    "platformio.ini"             => '\u{e682}'             , // 
    "build.zig.zon"              => '\u{e6a9}'             , // 
    ".prettierignore"            => '\u{e6b4}'             , // 
    ".prettierrc"                => '\u{e6b4}'             , // 
    ".prettierrc.json"           => '\u{e6b4}'             , // 
    ".prettierrc.json5"          => '\u{e6b4}'             , // 
    ".prettierrc.toml"           => '\u{e6b4}'             , // 
    ".prettierrc.yaml"           => '\u{e6b4}'             , // 
    ".prettierrc.yml"            => '\u{e6b4}'             , // 
    "dropbox"                    => '\u{e707}'             , // 
    ".condarc"                   => '\u{e715}'             , // 
    ".atom"                      => '\u{e764}'             , // 
    "bun.lockb"                  => '\u{e76f}'             , // 
    "heroku.yml"                 => '\u{e77b}'             , // 
    "Procfile"                   => '\u{e77b}'             , // 
    "CMakeLists.txt"             => '\u{e794}'             , // 
    ".nanorc"                    => '\u{e838}'             , // 
    "AUTHORS"                    => '\u{edca}'             , // 
    "AUTHORS.txt"                => '\u{edca}'             , // 
    "index.theme"                => '\u{ee72}'             , // 
    ".stowrc"                    => '\u{eef1}'             , // 
    "renovate.json"              => '\u{f027c}'            , // 󰉼
    "SECURITY"                   => '\u{f0483}'            , // 󰒃
    "SECURITY.md"                => '\u{f0483}'            , // 󰒃
    ".codespellrc"               => '\u{f04c6}'            , // 󰓆
    "vlcrc"                      => '\u{f057c}'            , // 󰕼
    "robots.txt"                 => '\u{f06a9}'            , // 󰚩
    ".pre-commit-config.yaml"    => '\u{f06e2}'            , // 󰛢
    "webpack.config.js"          => '\u{f072b}'            , // 󰜫
    "authorized_keys"            => '\u{f08c0}'            , // 󰣀
    "known_hosts"                => '\u{f08c0}'            , // 󰣀
    "Earthfile"                  => '\u{f0ac}'             , // 
    ".nuxtrc"                    => '\u{f1106}'            , // 󱄆
    "Brewfile"                   => '\u{f1116}'            , // 󱄖
    "Brewfile.lock.json"         => '\u{f1116}'            , // 󱄖
    ".gcloudignore"              => '\u{f11f6}'            , // 󱇶
    ".gitlab-ci.yml"             => '\u{f296}'             , // 
    ".SRCINFO"                   => '\u{f303}'             , // 
    "PKGBUILD"                   => '\u{f303}'             , // 
    "flake.lock"                 => '\u{f313}'             , // 
    "PrusaSlicer.ini"            => '\u{f351}'             , // 
    "PrusaSlicerGcodeViewer.ini" => '\u{f351}'             , // 
    "bspwmrc"                    => '\u{f355}'             , // 
    "hypridle.conf"              => '\u{f359}'             , // 
    "hyprland.conf"              => '\u{f359}'             , // 
    "hyprlock.conf"              => '\u{f359}'             , // 
    "hyprpaper.conf"             => '\u{f359}'             , // 
    "i3blocks.conf"              => '\u{f35a}'             , // 
    "i3status.conf"              => '\u{f35a}'             , // 
    "lxde-rc.xml"                => '\u{f363}'             , // 
    "lxqt.conf"                  => '\u{f364}'             , // 
    "weston.ini"                 => '\u{f367}'             , // 
    "mpv.conf"                   => '\u{f36e}'             , // 
    "cantorrc"                   => '\u{f373}'             , // 
    "kalgebrarc"                 => '\u{f373}'             , // 
    "kdeglobals"                 => '\u{f373}'             , // 
    ".envrc"                     => '\u{f462}'             , // 
    "CODE_OF_CONDUCT"            => '\u{f4ae}'             , // 
    "CODE_OF_CONDUCT.md"         => '\u{f4ae}'             , // 
    "localtime"                  => Icons::CLOCK           , // 
    "timezone"                   => Icons::CLOCK           , // 
    ".clang-format"              => Icons::CONFIG          , // 󱁻
    ".clang-tidy"                => Icons::CONFIG          , // 󱁻
    ".htaccess"                  => Icons::CONFIG          , // 󱁻
    ".htpasswd"                  => Icons::CONFIG          , // 󱁻
    ".inputrc"                   => Icons::CONFIG          , // 󱁻
    ".luacheckrc"                => Icons::CONFIG          , // 󱁻
    ".luaurc"                    => Icons::CONFIG          , // 󱁻
    ".pylintrc"                  => Icons::CONFIG          , // 󱁻
    "config"                     => Icons::CONFIG          , // 󱁻
    "config.status"              => Icons::CONFIG          , // 󱁻
    "configure.ac"               => Icons::CONFIG          , // 󱁻
    "configure.in"               => Icons::CONFIG          , // 󱁻
    "crontab"                    => Icons::CONFIG          , // 󱁻
    "crypttab"                   => Icons::CONFIG          , // 󱁻
    "environment"                => Icons::CONFIG          , // 󱁻
    "hostname"                   => Icons::CONFIG          , // 󱁻
    "inputrc"                    => Icons::CONFIG          , // 󱁻
    "shells"                     => Icons::CONFIG          , // 󱁻
    "sxhkdrc"                    => Icons::CONFIG          , // 
    "docker-compose.yml"         => Icons::DOCKER          , // 
    "Dockerfile"                 => Icons::DOCKER          , // 
    "compose.yaml"               => Icons::DOCKER          , // 
    "compose.yml"                => Icons::DOCKER          , // 
    "docker-compose.yaml"        => Icons::DOCKER          , // 
    ".emacs"                     => Icons::EMACS           , // 
    ".eslintignore"              => Icons::ESLINT          , // 
    ".eslintrc.cjs"              => Icons::ESLINT          , // 
    ".eslintrc.js"               => Icons::ESLINT          , // 
    ".eslintrc.json"             => Icons::ESLINT          , // 
    ".eslintrc.yaml"             => Icons::ESLINT          , // 
    ".eslintrc.yml"              => Icons::ESLINT          , // 
    "fonts.conf"                 => Icons::FONT            , // 
    "FreeCAD.conf"               => Icons::FREECAD         , // 
    ".gitattributes"             => Icons::GIT             , // 󰊢
    ".git-blame-ignore-revs"     => Icons::GIT             , // 󰊢
    ".gitconfig"                 => Icons::GIT             , // 󰊢
    ".gitignore"                 => Icons::GIT             , // 󰊢
    ".gitignore_global"          => Icons::GIT             , // 󰊢
    ".gitmodules"                => Icons::GIT             , // 󰊢
    ".mailmap"                   => Icons::GIT             , // 󰊢
    "COMMIT_EDITMSG"             => Icons::GIT             , // 
    "settings.gradle.kts"        => Icons::GRADLE          , // 
    "build.gradle.kts"           => Icons::GRADLE          , // 
    "gradle"                     => Icons::GRADLE          , // 
    "gradle.properties"          => Icons::GRADLE          , // 
    "gradlew"                    => Icons::GRADLE          , // 
    "gradlew.bat"                => Icons::GRADLE          , // 
    "gruntfile.coffee"           => Icons::GRUNT           , // 
    "gruntfile.js"               => Icons::GRUNT           , // 
    "gruntfile.ls"               => Icons::GRUNT           , // 
    ".gtkrc-2.0"                 => Icons::GTK             , // 
    "gtkrc"                      => Icons::GTK             , // 
    "gulpfile.coffee"            => Icons::GULP            , // 
    "gulpfile.js"                => Icons::GULP            , // 
    "gulpfile.ls"                => Icons::GULP            , // 
    ".idea"                      => Icons::INTELLIJ        , // 
    "kdenlive-layoutsrc"         => Icons::KDENLIVE        , // 
    "kdenliverc"                 => Icons::KDENLIVE        , // 
    "fp-info-cache"              => Icons::KICAD           , // 
    "fp-lib-table"               => Icons::KICAD           , // 
    "sym-lib-table"              => Icons::KICAD           , // 
    "kritadisplayrc"             => Icons::KRITA           , // 
    "kritarc"                    => Icons::KRITA           , // 
    "mix.lock"                   => Icons::LANG_ELIXIR     , // 
    ".fennelrc"                  => Icons::LANG_FENNEL     , // 
    "fennelrc"                   => Icons::LANG_FENNEL     , // 
    "go.mod"                     => Icons::LANG_GO         , // 
    "go.sum"                     => Icons::LANG_GO         , // 
    "go.work"                    => Icons::LANG_GO         , // 
    "jsconfig.json"              => Icons::LANG_JAVASCRIPT , // 
    ".ocamlinit"                 => Icons::LANG_OCAML      , // 
    "dune"                       => Icons::LANG_OCAML      , // 
    "composer.json"              => Icons::LANG_PHP        , // 
    "composer.lock"              => Icons::LANG_PHP        , // 
    "php.ini"                    => Icons::LANG_PHP        , // 
    ".python_history"            => Icons::LANG_PYTHON     , // 
    "constraints.txt"            => Icons::LANG_PYTHON     , // 
    "MANIFEST"                   => Icons::LANG_PYTHON     , // 
    "MANIFEST.in"                => Icons::LANG_PYTHON     , // 
    "pyvenv.cfg"                 => Icons::LANG_PYTHON     , // 
    "pyproject.toml"             => Icons::LANG_PYTHON     , // 
    "requirements.txt"           => Icons::LANG_PYTHON     , // 
    ".rvm"                       => Icons::LANG_RUBY       , // 
    ".rvmrc"                     => Icons::LANG_RUBY       , // 
    "config.ru"                  => Icons::LANG_RUBY       , // 
    "Gemfile"                    => Icons::LANG_RUBY       , // 
    "Gemfile.lock"               => Icons::LANG_RUBY       , // 
    "Rakefile"                   => Icons::LANG_RUBY       , // 
    "rvmrc"                      => Icons::LANG_RUBY       , // 
    "rubydoc"                    => Icons::LANG_RUBYRAILS  , // 
    ".rustfmt.toml"              => Icons::LANG_RUST       , // 
    "Cargo.lock"                 => Icons::LANG_RUST       , // 
    "Cargo.toml"                 => Icons::LANG_RUST       , // 
    "release.toml"               => Icons::LANG_RUST       , // 
    "tsconfig.json"              => Icons::LANG_TYPESCRIPT , // 
    "COPYING"                    => Icons::LICENSE         , // 
    "COPYRIGHT"                  => Icons::LICENSE         , // 
    "LICENCE"                    => Icons::LICENSE         , // 
    "LICENCE.md"                 => Icons::LICENSE         , // 
    "LICENCE.txt"                => Icons::LICENSE         , // 
    "LICENSE"                    => Icons::LICENSE         , // 
    "LICENSE-APACHE"             => Icons::LICENSE         , // 
    "LICENSE-MIT"                => Icons::LICENSE         , // 
    "LICENSE.md"                 => Icons::LICENSE         , // 
    "LICENSE.txt"                => Icons::LICENSE         , // 
    ".parentlock"                => Icons::LOCK            , // 
    "group"                      => Icons::LOCK            , // 
    "gshadow"                    => Icons::LOCK            , // 
    "lock"                       => Icons::LOCK            , // 
    "LOCK"                       => Icons::LOCK            , // 
    "passwd"                     => Icons::LOCK            , // 
    "shadow"                     => Icons::LOCK            , // 
    "sudoers"                    => Icons::LOCK            , // 
    "log"                        => Icons::LOG             , // 
    "LOG"                        => Icons::LOG             , // 
    "GNUmakefile"                => Icons::MAKE            , // 
    "Makefile"                   => Icons::MAKE            , // 
    "makefile"                   => Icons::MAKE            , // 
    "Makefile.ac"                => Icons::MAKE            , // 
    "Makefile.am"                => Icons::MAKE            , // 
    "Makefile.in"                => Icons::MAKE            , // 
    "CHANGELOG"                  => Icons::NEWS            , // 
    "CHANGELOG.md"               => Icons::NEWS            , // 
    "CHANGES"                    => Icons::NEWS            , // 
    "CHANGES.md"                 => Icons::NEWS            , // 
    "NEWS"                       => Icons::NEWS            , // 
    "NEWS.md"                    => Icons::NEWS            , // 
    ".node_repl_history"         => Icons::NODEJS          , // 
    ".npmignore"                 => Icons::NPM             , // 
    ".npmrc"                     => Icons::NPM             , // 
    "npm-shrinkwrap.json"        => Icons::NPM             , // 
    "npmrc"                      => Icons::NPM             , // 
    "package-lock.json"          => Icons::NPM             , // 
    "package.json"               => Icons::NPM             , // 
    ".CFUserTextEncoding"        => Icons::OS_APPLE        , // 
    ".DS_Store"                  => Icons::OS_APPLE        , // 
    "._DS_Store"                 => Icons::OS_APPLE        , // 
    "localized"                  => Icons::OS_APPLE        , // 
    "id_dsa"                     => Icons::PRIVATE_KEY     , // 󰌆
    "id_ecdsa"                   => Icons::PRIVATE_KEY     , // 󰌆
    "id_ecdsa_sk"                => Icons::PRIVATE_KEY     , // 󰌆
    "id_ed25519"                 => Icons::PRIVATE_KEY     , // 󰌆
    "id_ed25519_sk"              => Icons::PRIVATE_KEY     , // 󰌆
    "id_rsa"                     => Icons::PRIVATE_KEY     , // 󰌆
    "qt5ct.conf"                 => Icons::QT              , // 
    "qt6ct.conf"                 => Icons::QT              , // 
    "QtProject.conf"             => Icons::QT              , // 
    "README"                     => Icons::README          , // 󰂺
    "README.md"                  => Icons::README          , // 󰂺
    ".aliases"                   => Icons::SHELL           , // 󱆃
    ".bashrc"                    => Icons::SHELL           , // 󱆃
    ".bash_aliases"              => Icons::SHELL           , // 󱆃
    ".bash_history"              => Icons::SHELL           , // 󱆃
    ".bash_logout"               => Icons::SHELL           , // 󱆃
    ".bash_profile"              => Icons::SHELL           , // 󱆃
    ".cshrc"                     => Icons::SHELL           , // 󱆃
    ".kshrc"                     => Icons::SHELL           , // 󱆃
    ".login"                     => Icons::SHELL           , // 󱆃
    ".logout"                    => Icons::SHELL           , // 󱆃
    ".profile"                   => Icons::SHELL           , // 󱆃
    ".tcshrc"                    => Icons::SHELL           , // 󱆃
    ".zlogin"                    => Icons::SHELL           , // 󱆃
    ".zlogout"                   => Icons::SHELL           , // 󱆃
    ".zprofile"                  => Icons::SHELL           , // 󱆃
    ".zshenv"                    => Icons::SHELL           , // 󱆃
    ".zshrc"                     => Icons::SHELL           , // 󱆃
    ".zsh_history"               => Icons::SHELL           , // 󱆃
    ".zsh_sessions"              => Icons::SHELL           , // 󱆃
    "bashrc"                     => Icons::SHELL           , // 󱆃
    "csh.cshrc"                  => Icons::SHELL           , // 󱆃
    "csh.login"                  => Icons::SHELL           , // 󱆃
    "csh.logout"                 => Icons::SHELL           , // 󱆃
    "profile"                    => Icons::SHELL           , // 󱆃
    "zlogin"                     => Icons::SHELL           , // 󱆃
    "zlogout"                    => Icons::SHELL           , // 󱆃
    "zprofile"                   => Icons::SHELL           , // 󱆃
    "zshenv"                     => Icons::SHELL           , // 󱆃
    "zshrc"                      => Icons::SHELL           , // 󱆃
    "a.out"                      => Icons::SHELL_CMD       , // 
    "tmux.conf"                  => Icons::TMUX            , // 
    "tmux.conf.local"            => Icons::TMUX            , // 
    "TODO"                       => Icons::TODO            , // 
    "TODO.md"                    => Icons::TODO            , // 
    ".gvimrc"                    => Icons::VIM             , // 
    "_gvimrc"                    => Icons::VIM             , // 
    "_vimrc"                     => Icons::VIM             , // 
    ".ideavimrc"                 => Icons::VIM             , // 
    ".viminfo"                   => Icons::VIM             , // 
    ".vimrc"                     => Icons::VIM             , // 
    "configure"                  => Icons::WRENCH          , // 
    "dune-project"               => Icons::WRENCH          , // 
    "Justfile"                   => Icons::WRENCH          , // 
    "justfile"                   => Icons::WRENCH          , // 
    ".Xauthority"                => Icons::XORG            , // 
    ".xinitrc"                   => Icons::XORG            , // 
    ".Xresources"                => Icons::XORG            , // 
    ".xsession"                  => Icons::XORG            , // 
    "xorg.conf"                  => Icons::XORG            , // 
    "xsettingsd.conf"            => Icons::XORG            , // 
    "xmobarrc"                   => Icons::XORG            , // 
    "xmobarrc.hs"                => Icons::XORG            , // 
    "xmonad.hs"                  => Icons::XORG            , // 
    ".yarnrc"                    => Icons::YARN            , // 
    "yarn.lock"                  => Icons::YARN            , // 
};

/* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— */

/// Mapping from lowercase file extension to icons.  If an image, video, or audio extension is add
/// also update the extension filetype map.
const EXTENSION_ICONS: Map<&'static str, char> = phf_map! {
    "torrent"          => '\u{e275}'             , // 
    "ejs"              => '\u{e618}'             , // 
    "twig"             => '\u{e61c}'             , // 
    "jl"               => '\u{e624}'             , // 
    "com"              => '\u{e629}'             , // 
    "elm"              => '\u{e62c}'             , // 
    "cr"               => '\u{e62f}'             , // 
    "purs"             => '\u{e630}'             , // 
    "pp"               => '\u{e631}'             , // 
    "org"              => '\u{e633}'             , // 
    "cu"               => '\u{e64b}'             , // 
    "editorconfig"     => '\u{e652}'             , // 
    "haml"             => '\u{e664}'             , // 
    "svelte"           => '\u{e697}'             , // 
    "zig"              => '\u{e6a9}'             , // 
    "sln"              => '\u{e70c}'             , // 
    "suo"              => '\u{e70c}'             , // 
    "conda"            => '\u{e715}'             , // 
    "scala"            => '\u{e737}'             , // 
    "swift"            => '\u{e755}'             , // 
    "xcplayground"     => '\u{e755}'             , // 
    "less"             => '\u{e758}'             , // 
    "clj"              => '\u{e768}'             , // 
    "cljc"             => '\u{e768}'             , // 
    "cljs"             => '\u{e76a}'             , // 
    "edn"              => '\u{e76a}'             , // 
    "rdb"              => '\u{e76d}'             , // 
    "deb"              => '\u{e77d}'             , // 
    "cmake"            => '\u{e794}'             , // 
    "dart"             => '\u{e798}'             , // 
    "erl"              => '\u{e7b1}'             , // 
    "hrl"              => '\u{e7b1}'             , // 
    "ai"               => '\u{e7b4}'             , // 
    "psb"              => '\u{e7b8}'             , // 
    "psd"              => '\u{e7b8}'             , // 
    "rpm"              => '\u{e7bb}'             , // 
    "vi"               => '\u{e81e}'             , // 
    "norg"             => '\u{e847}'             , // 
    "vala"             => '\u{e8d1}'             , // 
    "xpi"              => '\u{eae6}'             , // 
    "pkg"              => '\u{eb29}'             , // 
    "out"              => '\u{eb2c}'             , // 
    "service"          => '\u{eba2}'             , // 
    "drawio"           => '\u{ebba}'             , // 
    "desktop"          => '\u{ebd1}'             , // 
    "csv"              => '\u{eefc}'             , // 
    "eml"              => '\u{f003}'             , // 
    "blend"            => '\u{f00ab}'            , // 󰂫
    "lisp"             => '\u{f0172}'            , // 󰅲
    "cow"              => '\u{f019a}'            , // 󰆚
    "opam"             => '\u{f0627}'            , // 󰘧
    "xaml"             => '\u{f0673}'            , // 󰙳
    "magnet"           => '\u{f076}'             , // 
    "ninja"            => '\u{f0774}'            , // 󰝴
    "nsp"              => '\u{F07E1}'            , // 󰟡
    "xci"              => '\u{F07E1}'            , // 󰟡
    "vue"              => '\u{f0844}'            , // 󰡄
    "mid"              => '\u{f08f2}'            , // 󰣲
    "rss"              => '\u{f09e}'             , // 
    "vhs"              => '\u{F0A1B}'            , // 󰨛
    "vsix"             => '\u{f0a1e}'            , // 󰨞
    "gcode"            => '\u{f0af4}'            , // 󰫴
    "coffee"           => '\u{f0f4}'             , // 
    "sf2"              => '\u{f0f70}'            , // 󰽰
    "sfz"              => '\u{f0f70}'            , // 󰽰
    "asp"              => '\u{f121}'             , // 
    "hex"              => '\u{f12a7}'            , // 󱊧
    "gba"              => '\u{f1393}'            , // 󱎓
    "z64"              => '\u{f1393}'            , // 󱎓
    "sal"              => '\u{f147b}'            , // 󱑻
    "sr"               => '\u{f147b}'            , // 󱑻
    "acf"              => '\u{f1b6}'             , // 
    "pdf"              => '\u{f1c1}'             , // 
    "gform"            => '\u{f298}'             , // 
    "ui"               => '\u{f2d0}'             , // 
    "ebuild"           => '\u{f30d}'             , // 
    "nix"              => '\u{f313}'             , // 
    "scad"             => '\u{f34e}'             , // 
    "jwmrc"            => '\u{f35b}'             , // 
    "msf"              => '\u{f370}'             , // 
    "fods"             => '\u{f378}'             , // 
    "ods"              => '\u{f378}'             , // 
    "fodg"             => '\u{f379}'             , // 
    "odg"              => '\u{f379}'             , // 
    "fodp"             => '\u{f37a}'             , // 
    "odp"              => '\u{f37a}'             , // 
    "odf"              => '\u{f37b}'             , // 
    "fodt"             => '\u{f37c}'             , // 
    "odt"              => '\u{f37c}'             , // 
    "env"              => '\u{f462}'             , // 
    "aac"              => Icons::AUDIO           , // 
    "aif"              => Icons::AUDIO           , // 
    "aifc"             => Icons::AUDIO           , // 
    "aiff"             => Icons::AUDIO           , // 
    "alac"             => Icons::AUDIO           , // 
    "ape"              => Icons::AUDIO           , // 
    "flac"             => Icons::AUDIO           , // 
    "m4a"              => Icons::AUDIO           , // 
    "mka"              => Icons::AUDIO           , // 
    "mp2"              => Icons::AUDIO           , // 
    "mp3"              => Icons::AUDIO           , // 
    "ogg"              => Icons::AUDIO           , // 
    "opus"             => Icons::AUDIO           , // 
    "pcm"              => Icons::AUDIO           , // 
    "swf"              => Icons::AUDIO           , // 
    "wav"              => Icons::AUDIO           , // 
    "wma"              => Icons::AUDIO           , // 
    "wv"               => Icons::AUDIO           , // 
    "app"              => Icons::BINARY          , // 
    "bin"              => Icons::BINARY          , // 
    "elf"              => Icons::BINARY          , // 
    "hi"               => Icons::BINARY          , // 
    "o"                => Icons::BINARY          , // 
    "ebook"            => Icons::BOOK            , // 
    "epub"             => Icons::BOOK            , // 
    "mobi"             => Icons::BOOK            , // 
    "cache"            => Icons::CACHE           , // 
    "123dx"            => Icons::CAD             , // 󰻫
    "3dm"              => Icons::CAD             , // 󰻫
    "brep"             => Icons::CAD             , // 󰻫
    "catpart"          => Icons::CAD             , // 󰻫
    "catproduct"       => Icons::CAD             , // 󰻫
    "dwg"              => Icons::CAD             , // 󰻫
    "dxf"              => Icons::CAD             , // 󰻫
    "f3d"              => Icons::CAD             , // 󰻫
    "f3z"              => Icons::CAD             , // 󰻫
    "iam"              => Icons::CAD             , // 󰻫
    "ifc"              => Icons::CAD             , // 󰻫
    "ige"              => Icons::CAD             , // 󰻫
    "iges"             => Icons::CAD             , // 󰻫
    "igs"              => Icons::CAD             , // 󰻫
    "ipt"              => Icons::CAD             , // 󰻫
    "psm"              => Icons::CAD             , // 󰻫
    "skp"              => Icons::CAD             , // 󰻫
    "sldasm"           => Icons::CAD             , // 󰻫
    "sldprt"           => Icons::CAD             , // 󰻫
    "slvs"             => Icons::CAD             , // 󰻫
    "ste"              => Icons::CAD             , // 󰻫
    "step"             => Icons::CAD             , // 󰻫
    "stp"              => Icons::CAD             , // 󰻫
    "x_b"              => Icons::CAD             , // 󰻫
    "x_t"              => Icons::CAD             , // 󰻫
    "ical"             => Icons::CALENDAR        , // 
    "icalendar"        => Icons::CALENDAR        , // 
    "ics"              => Icons::CALENDAR        , // 
    "ifb"              => Icons::CALENDAR        , // 
    "7z"               => Icons::COMPRESSED      , // 
    "ar"               => Icons::COMPRESSED      , // 
    "arj"              => Icons::COMPRESSED      , // 
    "br"               => Icons::COMPRESSED      , // 
    "bz"               => Icons::COMPRESSED      , // 
    "bz2"              => Icons::COMPRESSED      , // 
    "bz3"              => Icons::COMPRESSED      , // 
    "cpio"             => Icons::COMPRESSED      , // 
    "gz"               => Icons::COMPRESSED      , // 
    "lz"               => Icons::COMPRESSED      , // 
    "lz4"              => Icons::COMPRESSED      , // 
    "lzh"              => Icons::COMPRESSED      , // 
    "lzma"             => Icons::COMPRESSED      , // 
    "lzo"              => Icons::COMPRESSED      , // 
    "par"              => Icons::COMPRESSED      , // 
    "rar"              => Icons::COMPRESSED      , // 
    "tar"              => Icons::COMPRESSED      , // 
    "taz"              => Icons::COMPRESSED      , // 
    "tbz"              => Icons::COMPRESSED      , // 
    "tbz2"             => Icons::COMPRESSED      , // 
    "tgz"              => Icons::COMPRESSED      , // 
    "tlz"              => Icons::COMPRESSED      , // 
    "txz"              => Icons::COMPRESSED      , // 
    "tz"               => Icons::COMPRESSED      , // 
    "tzo"              => Icons::COMPRESSED      , // 
    "xz"               => Icons::COMPRESSED      , // 
    "z"                => Icons::COMPRESSED      , // 
    "zip"              => Icons::COMPRESSED      , // 
    "zst"              => Icons::COMPRESSED      , // 
    "cfg"              => Icons::CONFIG          , // 󱁻
    "conf"             => Icons::CONFIG          , // 󱁻
    "config"           => Icons::CONFIG          , // 󱁻
    "ini"              => Icons::CONFIG          , // 󱁻
    "tml"              => Icons::CONFIG          , // 
    "css"              => Icons::CSS3            , // 
    "dump"             => Icons::DATABASE        , // 
    "ldb"              => Icons::DATABASE        , // 
    "mdb"              => Icons::DATABASE        , // 
    "odb"              => Icons::DATABASE        , // 
    "prql"             => Icons::DATABASE        , // 
    "sql"              => Icons::DATABASE        , // 
    "db"               => Icons::DATABASE        , // 
    "dconf"            => Icons::DATABASE        , // 
    "diff"             => Icons::DIFF            , // 
    "patch"            => Icons::DIFF            , // 
    "dmg"              => Icons::DISK_IMAGE      , // 
    "image"            => Icons::DISK_IMAGE      , // 
    "img"              => Icons::DISK_IMAGE      , // 
    "iso"              => Icons::DISK_IMAGE      , // 
    "qcow"             => Icons::DISK_IMAGE      , // 
    "qcow2"            => Icons::DISK_IMAGE      , // 
    "tc"               => Icons::DISK_IMAGE      , // 
    "vdi"              => Icons::DISK_IMAGE      , // 
    "vhd"              => Icons::DISK_IMAGE      , // 
    "vmdk"             => Icons::DISK_IMAGE      , // 
    "dockerfile"       => Icons::DOCKER          , // 
    "dockerignore"     => Icons::DOCKER          , // 
    "djv"              => Icons::DOCUMENT        , // 
    "djvu"             => Icons::DOCUMENT        , // 
    "doc"              => Icons::DOCUMENT        , // 
    "docm"             => Icons::DOCUMENT        , // 
    "docx"             => Icons::DOCUMENT        , // 
    "gdoc"             => Icons::DOCUMENT        , // 
    "crdownload"       => Icons::DOWNLOAD        , // 󰇚
    "download"         => Icons::DOWNLOAD        , // 󰇚
    "fdmdownload"      => Icons::DOWNLOAD        , // 󰇚
    "part"             => Icons::DOWNLOAD        , // 󰇚
    "brd"              => Icons::EDA_PCB         , // 
    "gbl"              => Icons::EDA_PCB         , // 
    "gbo"              => Icons::EDA_PCB         , // 
    "gbp"              => Icons::EDA_PCB         , // 
    "gbr"              => Icons::EDA_PCB         , // 
    "gbs"              => Icons::EDA_PCB         , // 
    "gm1"              => Icons::EDA_PCB         , // 
    "gml"              => Icons::EDA_PCB         , // 
    "gtl"              => Icons::EDA_PCB         , // 
    "gto"              => Icons::EDA_PCB         , // 
    "gtp"              => Icons::EDA_PCB         , // 
    "gts"              => Icons::EDA_PCB         , // 
    "lpp"              => Icons::EDA_PCB         , // 
    "pcbdoc"           => Icons::EDA_PCB         , // 
    "prjpcb"           => Icons::EDA_PCB         , // 
    "sch"              => Icons::EDA_SCH         , // 󰭅
    "schdoc"           => Icons::EDA_SCH         , // 󰭅
    "el"               => Icons::EMACS           , // 
    "elc"              => Icons::EMACS           , // 
    "3mf"              => Icons::FILE_3D         , // 󰆧
    "fbx"              => Icons::FILE_3D         , // 󰆧
    "obj"              => Icons::FILE_3D         , // 󰆧
    "ply"              => Icons::FILE_3D         , // 󰆧
    "stl"              => Icons::FILE_3D         , // 󰆧
    "wrl"              => Icons::FILE_3D         , // 󰆧
    "wrz"              => Icons::FILE_3D         , // 󰆧
    "bdf"              => Icons::FONT            , // 
    "eot"              => Icons::FONT            , // 
    "flc"              => Icons::FONT            , // 
    "flf"              => Icons::FONT            , // 
    "fnt"              => Icons::FONT            , // 
    "fon"              => Icons::FONT            , // 
    "font"             => Icons::FONT            , // 
    "lff"              => Icons::FONT            , // 
    "otf"              => Icons::FONT            , // 
    "psf"              => Icons::FONT            , // 
    "ttc"              => Icons::FONT            , // 
    "ttf"              => Icons::FONT            , // 
    "woff"             => Icons::FONT            , // 
    "woff2"            => Icons::FONT            , // 
    "fcbak"            => Icons::FREECAD         , // 
    "fcmacro"          => Icons::FREECAD         , // 
    "fcmat"            => Icons::FREECAD         , // 
    "fcparam"          => Icons::FREECAD         , // 
    "fcscript"         => Icons::FREECAD         , // 
    "fcstd"            => Icons::FREECAD         , // 
    "fcstd1"           => Icons::FREECAD         , // 
    "fctb"             => Icons::FREECAD         , // 
    "fctl"             => Icons::FREECAD         , // 
    "xcf"              => Icons::GIMP            , // 
    "cert"             => Icons::GIST_SECRET     , // 
    "crt"              => Icons::GIST_SECRET     , // 
    "git"              => Icons::GIT             , // 󰊢
    "gd"               => Icons::GODOT           , // 
    "godot"            => Icons::GODOT           , // 
    "tres"             => Icons::GODOT           , // 
    "tscn"             => Icons::GODOT           , // 
    "gradle"           => Icons::GRADLE          , // 
    "dot"              => Icons::GRAPH           , // 󱁉
    "gv"               => Icons::GRAPH           , // 󱁉
    "gql"              => Icons::GRAPHQL         , // 
    "graphql"          => Icons::GRAPHQL         , // 
    "gresource"        => Icons::GTK             , // 
    "htm"              => Icons::HTML5           , // 
    "html"             => Icons::HTML5           , // 
    "shtml"            => Icons::HTML5           , // 
    "xhtml"            => Icons::HTML5           , // 
    "arw"              => Icons::IMAGE           , // 
    "avif"             => Icons::IMAGE           , // 
    "bmp"              => Icons::IMAGE           , // 
    "cbr"              => Icons::IMAGE           , // 
    "cbz"              => Icons::IMAGE           , // 
    "cr2"              => Icons::IMAGE           , // 
    "dvi"              => Icons::IMAGE           , // 
    "gif"              => Icons::IMAGE           , // 
    "heic"             => Icons::IMAGE           , // 
    "heif"             => Icons::IMAGE           , // 
    "ico"              => Icons::IMAGE           , // 
    "j2c"              => Icons::IMAGE           , // 
    "j2k"              => Icons::IMAGE           , // 
    "jfi"              => Icons::IMAGE           , // 
    "jfif"             => Icons::IMAGE           , // 
    "jif"              => Icons::IMAGE           , // 
    "jp2"              => Icons::IMAGE           , // 
    "jpe"              => Icons::IMAGE           , // 
    "jpeg"             => Icons::IMAGE           , // 
    "jpf"              => Icons::IMAGE           , // 
    "jpg"              => Icons::IMAGE           , // 
    "jpx"              => Icons::IMAGE           , // 
    "jxl"              => Icons::IMAGE           , // 
    "nef"              => Icons::IMAGE           , // 
    "orf"              => Icons::IMAGE           , // 
    "pbm"              => Icons::IMAGE           , // 
    "pgm"              => Icons::IMAGE           , // 
    "png"              => Icons::IMAGE           , // 
    "pnm"              => Icons::IMAGE           , // 
    "ppm"              => Icons::IMAGE           , // 
    "pxm"              => Icons::IMAGE           , // 
    "raw"              => Icons::IMAGE           , // 
    "tif"              => Icons::IMAGE           , // 
    "tiff"             => Icons::IMAGE           , // 
    "webp"             => Icons::IMAGE           , // 
    "xpm"              => Icons::IMAGE           , // 
    "info"             => Icons::INFO            , // 
    "nfo"              => Icons::INFO            , // 
    "iml"              => Icons::INTELLIJ        , // 
    "avro"             => Icons::JSON            , // 
    "json"             => Icons::JSON            , // 
    "json5"            => Icons::JSON            , // 
    "jsonc"            => Icons::JSON            , // 
    "properties"       => Icons::JSON            , // 
    "webmanifest"      => Icons::JSON            , // 
    "kdenlive"         => Icons::KDENLIVE        , // 
    "kdenlivetitle"    => Icons::KDENLIVE        , // 
    "key"              => Icons::KEY             , // 
    "p12"              => Icons::KEY             , // 
    "pem"              => Icons::KEY             , // 
    "pfx"              => Icons::KEY             , // 
    "kdb"              => Icons::KEYPASS         , // 
    "kdbx"             => Icons::KEYPASS         , // 
    "kicad_dru"        => Icons::KICAD           , // 
    "kicad_mod"        => Icons::KICAD           , // 
    "kicad_pcb"        => Icons::KICAD           , // 
    "kicad_prl"        => Icons::KICAD           , // 
    "kicad_pro"        => Icons::KICAD           , // 
    "kicad_sch"        => Icons::KICAD           , // 
    "kicad_sym"        => Icons::KICAD           , // 
    "kicad_wks"        => Icons::KICAD           , // 
    "kpp"              => Icons::KRITA           , // 
    "kra"              => Icons::KRITA           , // 
    "krz"              => Icons::KRITA           , // 
    "ino"              => Icons::LANG_ARDUINO    , // 
    "asm"              => Icons::LANG_ASSEMBLY   , // 
    "s"                => Icons::LANG_ASSEMBLY   , // 
    "c"                => Icons::LANG_C          , // 
    "h"                => Icons::LANG_C          , // 
    "inl"              => Icons::LANG_C          , // 
    "m"                => Icons::LANG_C          , // 
    "c++"              => Icons::LANG_CPP        , // 
    "cc"               => Icons::LANG_CPP        , // 
    "cp"               => Icons::LANG_CPP        , // 
    "cpp"              => Icons::LANG_CPP        , // 
    "cxx"              => Icons::LANG_CPP        , // 
    "h++"              => Icons::LANG_CPP        , // 
    "hh"               => Icons::LANG_CPP        , // 
    "hpp"              => Icons::LANG_CPP        , // 
    "hxx"              => Icons::LANG_CPP        , // 
    "mm"               => Icons::LANG_CPP        , // 
    "cs"               => Icons::LANG_CSHARP     , // 󰌛
    "csproj"           => Icons::LANG_CSHARP     , // 󰌛
    "csx"              => Icons::LANG_CSHARP     , // 󰌛
    "d"                => Icons::LANG_D          , // 
    "di"               => Icons::LANG_D          , // 
    "eex"              => Icons::LANG_ELIXIR     , // 
    "ex"               => Icons::LANG_ELIXIR     , // 
    "exs"              => Icons::LANG_ELIXIR     , // 
    "leex"             => Icons::LANG_ELIXIR     , // 
    "fnl"              => Icons::LANG_FENNEL     , // 
    "f"                => Icons::LANG_FORTRAN    , // 󱈚
    "f90"              => Icons::LANG_FORTRAN    , // 󱈚
    "for"              => Icons::LANG_FORTRAN    , // 󱈚
    "f#"               => Icons::LANG_FSHARP     , // 
    "fs"               => Icons::LANG_FSHARP     , // 
    "fsi"              => Icons::LANG_FSHARP     , // 
    "fsproj"           => Icons::LANG_FSHARP     , // 
    "fsscript"         => Icons::LANG_FSHARP     , // 
    "fsx"              => Icons::LANG_FSHARP     , // 
    "gleam"            => Icons::LANG_GLEAM      , // 󰦥
    "go"               => Icons::LANG_GO         , // 
    "groovy"           => Icons::LANG_GROOVY     , // 
    "gvy"              => Icons::LANG_GROOVY     , // 
    "hs"               => Icons::LANG_HASKELL    , // 
    "lhs"              => Icons::LANG_HASKELL    , // 
    "sv"               => Icons::LANG_HDL        , // 󰍛
    "svh"              => Icons::LANG_HDL        , // 󰍛
    "vhdl"             => Icons::LANG_HDL        , // 󰍛
    "hc"               => Icons::LANG_HOLYC      , // 󰂢
    "class"            => Icons::LANG_JAVA       , // 
    "jad"              => Icons::LANG_JAVA       , // 
    "jar"              => Icons::LANG_JAVA       , // 
    "java"             => Icons::LANG_JAVA       , // 
    "war"              => Icons::LANG_JAVA       , // 
    "cjs"              => Icons::LANG_JAVASCRIPT , // 
    "js"               => Icons::LANG_JAVASCRIPT , // 
    "mjs"              => Icons::LANG_JAVASCRIPT , // 
    "kt"               => Icons::LANG_KOTLIN     , // 
    "kts"              => Icons::LANG_KOTLIN     , // 
    "lua"              => Icons::LANG_LUA        , // 
    "luac"             => Icons::LANG_LUA        , // 
    "luau"             => Icons::LANG_LUA        , // 
    "nim"              => Icons::LANG_NIM        , // 
    "nimble"           => Icons::LANG_NIM        , // 
    "nims"             => Icons::LANG_NIM        , // 
    "ml"               => Icons::LANG_OCAML      , // 
    "mli"              => Icons::LANG_OCAML      , // 
    "mll"              => Icons::LANG_OCAML      , // 
    "mly"              => Icons::LANG_OCAML      , // 
    "pl"               => Icons::LANG_PERL       , // 
    "plx"              => Icons::LANG_PERL       , // 
    "pm"               => Icons::LANG_PERL       , // 
    "pod"              => Icons::LANG_PERL       , // 
    "t"                => Icons::LANG_PERL       , // 
    "phar"             => Icons::LANG_PHP        , // 
    "php"              => Icons::LANG_PHP        , // 
    "pxd"              => Icons::LANG_PYTHON     , // 
    "py"               => Icons::LANG_PYTHON     , // 
    "pyc"              => Icons::LANG_PYTHON     , // 
    "pyd"              => Icons::LANG_PYTHON     , // 
    "pyi"              => Icons::LANG_PYTHON     , // 
    "pyo"              => Icons::LANG_PYTHON     , // 
    "pyw"              => Icons::LANG_PYTHON     , // 
    "pyx"              => Icons::LANG_PYTHON     , // 
    "whl"              => Icons::LANG_PYTHON     , // 
    "r"                => Icons::LANG_R          , // 
    "rdata"            => Icons::LANG_R          , // 
    "rds"              => Icons::LANG_R          , // 
    "gem"              => Icons::LANG_RUBY       , // 
    "gemfile"          => Icons::LANG_RUBY       , // 
    "gemspec"          => Icons::LANG_RUBY       , // 
    "guardfile"        => Icons::LANG_RUBY       , // 
    "procfile"         => Icons::LANG_RUBY       , // 
    "rake"             => Icons::LANG_RUBY       , // 
    "rakefile"         => Icons::LANG_RUBY       , // 
    "rb"               => Icons::LANG_RUBY       , // 
    "rspec"            => Icons::LANG_RUBY       , // 
    "rspec_parallel"   => Icons::LANG_RUBY       , // 
    "rspec_status"     => Icons::LANG_RUBY       , // 
    "ru"               => Icons::LANG_RUBY       , // 
    "erb"              => Icons::LANG_RUBYRAILS  , // 
    "rubydoc"          => Icons::LANG_RUBYRAILS  , // 
    "slim"             => Icons::LANG_RUBYRAILS  , // 
    "rlib"             => Icons::LANG_RUST       , // 
    "rmeta"            => Icons::LANG_RUST       , // 
    "rs"               => Icons::LANG_RUST       , // 
    "sass"             => Icons::LANG_SASS       , // 
    "scss"             => Icons::LANG_SASS       , // 
    "rkt"              => Icons::LANG_SCHEME     , // 
    "scm"              => Icons::LANG_SCHEME     , // 
    "sld"              => Icons::LANG_SCHEME     , // 
    "ss"               => Icons::LANG_SCHEME     , // 
    "styl"             => Icons::LANG_STYLUS     , // 
    "stylus"           => Icons::LANG_STYLUS     , // 
    "bib"              => Icons::LANG_TEX        , // 
    "bst"              => Icons::LANG_TEX        , // 
    "cls"              => Icons::LANG_TEX        , // 
    "latex"            => Icons::LANG_TEX        , // 
    "ltx"              => Icons::LANG_TEX        , // 
    "sty"              => Icons::LANG_TEX        , // 
    "tex"              => Icons::LANG_TEX        , // 
    "cts"              => Icons::LANG_TYPESCRIPT , // 
    "mts"              => Icons::LANG_TYPESCRIPT , // 
    "ts"               => Icons::LANG_TYPESCRIPT , // 
    "v"                => Icons::LANG_V          , // 
    "dll"              => Icons::LIBRARY         , // 
    "lbr"              => Icons::LIBRARY         , // 
    "lib"              => Icons::LIBRARY         , // 
    "license"          => Icons::LICENSE         , // 
    "lck"              => Icons::LOCK            , // 
    "lock"             => Icons::LOCK            , // 
    "log"              => Icons::LOG             , // 
    "mk"               => Icons::MAKE            , // 
    "rmd"              => Icons::MARKDOWN        , // 
    "jmd"              => Icons::MARKDOWN        , // 
    "markdown"         => Icons::MARKDOWN        , // 
    "md"               => Icons::MARKDOWN        , // 
    "mdx"              => Icons::MARKDOWN        , // 
    "mkd"              => Icons::MARKDOWN        , // 
    "rdoc"             => Icons::MARKDOWN        , // 
    "hbs"              => Icons::MUSTACHE        , // 
    "mustache"         => Icons::MUSTACHE        , // 
    "node"             => Icons::NODEJS          , // 
    "ipynb"            => Icons::NOTEBOOK        , // 
    "android"          => Icons::OS_ANDROID      , // 
    "apk"              => Icons::OS_ANDROID      , // 
    "applescript"      => Icons::OS_APPLE        , // 
    "apple"            => Icons::OS_APPLE        , // 
    "bundle"           => Icons::OS_APPLE        , // 
    "dylib"            => Icons::OS_APPLE        , // 
    "localized"        => Icons::OS_APPLE        , // 
    "plist"            => Icons::OS_APPLE        , // 
    "a"                => Icons::OS_LINUX        , // 
    "ko"               => Icons::OS_LINUX        , // 
    "so"               => Icons::OS_LINUX        , // 
    "cab"              => Icons::OS_WINDOWS      , // 
    "cmd"              => Icons::OS_WINDOWS      , // 
    "msi"              => Icons::OS_WINDOWS      , // 
    "windows"          => Icons::OS_WINDOWS      , // 
    "bat"              => Icons::OS_WINDOWS_CMD  , // 
    "exe"              => Icons::OS_WINDOWS_CMD  , // 
    "cue"              => Icons::PLAYLIST        , // 󰲹
    "m3u"              => Icons::PLAYLIST        , // 󰲹
    "m3u8"             => Icons::PLAYLIST        , // 󰲹
    "pls"              => Icons::PLAYLIST        , // 󰲹
    "ps1"              => Icons::POWERSHELL      , // 
    "psd1"             => Icons::POWERSHELL      , // 
    "psm1"             => Icons::POWERSHELL      , // 
    "pub"              => Icons::PUBLIC_KEY      , // 󰷖
    "qml"              => Icons::QT              , // 
    "qrc"              => Icons::QT              , // 
    "qss"              => Icons::QT              , // 
    "cshtml"           => Icons::RAZOR           , // 
    "razor"            => Icons::RAZOR           , // 
    "jsx"              => Icons::REACT           , // 
    "tsx"              => Icons::REACT           , // 
    "readme"           => Icons::README          , // 󰂺
    "gsheet"           => Icons::SHEET           , // 
    "tsv"              => Icons::SHEET           , // 
    "xlr"              => Icons::SHEET           , // 
    "xls"              => Icons::SHEET           , // 
    "xlsm"             => Icons::SHEET           , // 
    "xlsx"             => Icons::SHEET           , // 
    "zsh-theme"        => Icons::SHELL           , // 󱆃
    "awk"              => Icons::SHELL_CMD       , // 
    "bash"             => Icons::SHELL_CMD       , // 
    "bats"             => Icons::SHELL_CMD       , // 
    "csh"              => Icons::SHELL_CMD       , // 
    "fish"             => Icons::SHELL_CMD       , // 
    "ksh"              => Icons::SHELL_CMD       , // 
    "nu"               => Icons::SHELL_CMD       , // 
    "sh"               => Icons::SHELL_CMD       , // 
    "shell"            => Icons::SHELL_CMD       , // 
    "zsh"              => Icons::SHELL_CMD       , // 
    "md5"              => Icons::SHIELD_CHECK    , // 󰕥
    "sha1"             => Icons::SHIELD_CHECK    , // 󰕥
    "sha224"           => Icons::SHIELD_CHECK    , // 󰕥
    "sha256"           => Icons::SHIELD_CHECK    , // 󰕥
    "sha384"           => Icons::SHIELD_CHECK    , // 󰕥
    "sha512"           => Icons::SHIELD_CHECK    , // 󰕥
    "kbx"              => Icons::SHIELD_KEY      , // 󰯄
    "age"              => Icons::SHIELD_LOCK     , // 󰦝
    "asc"              => Icons::SHIELD_LOCK     , // 󰦝
    "gpg"              => Icons::SHIELD_LOCK     , // 󰦝
    "sig"              => Icons::SIGNED_FILE     , // 󱧃
    "signature"        => Icons::SIGNED_FILE     , // 󱧃
    "gslides"          => Icons::SLIDE           , // 
    "pps"              => Icons::SLIDE           , // 
    "ppsx"             => Icons::SLIDE           , // 
    "ppt"              => Icons::SLIDE           , // 
    "pptx"             => Icons::SLIDE           , // 
    "db3"              => Icons::SQLITE          , // 
    "s3db"             => Icons::SQLITE          , // 
    "sl3"              => Icons::SQLITE          , // 
    "sqlite"           => Icons::SQLITE          , // 
    "sqlite3"          => Icons::SQLITE          , // 
    "sublime-build"    => Icons::SUBLIME         , // 
    "sublime-keymap"   => Icons::SUBLIME         , // 
    "sublime-menu"     => Icons::SUBLIME         , // 
    "sublime-options"  => Icons::SUBLIME         , // 
    "sublime-package"  => Icons::SUBLIME         , // 
    "sublime-project"  => Icons::SUBLIME         , // 
    "sublime-session"  => Icons::SUBLIME         , // 
    "sublime-settings" => Icons::SUBLIME         , // 
    "sublime-snippet"  => Icons::SUBLIME         , // 
    "sublime-theme"    => Icons::SUBLIME         , // 
    "ass"              => Icons::SUBTITLE        , // 󰨖
    "lrc"              => Icons::SUBTITLE        , // 󰨖
    "sbt"              => Icons::SUBTITLE        , // 󰨖
    "srt"              => Icons::SUBTITLE        , // 󰨖
    "ssa"              => Icons::SUBTITLE        , // 󰨖
    "sub"              => Icons::SUBTITLE        , // 󰨖
    "tbc"              => Icons::TCL             , // 󰛓
    "tcl"              => Icons::TCL             , // 󰛓
    "tf"               => Icons::TERRAFORM       , // 󱁢
    "tfstate"          => Icons::TERRAFORM       , // 󱁢
    "tfvars"           => Icons::TERRAFORM       , // 󱁢
    "rst"              => Icons::TEXT            , // 
    "rtf"              => Icons::TEXT            , // 
    "txt"              => Icons::TEXT            , // 
    "tmux"             => Icons::TMUX            , // 
    "toml"             => Icons::TOML            , // 
    "mo"               => Icons::TRANSLATION     , // 󰗊
    "po"               => Icons::TRANSLATION     , // 󰗊
    "pot"              => Icons::TRANSLATION     , // 󰗊
    "qm"               => Icons::TRANSLATION     , // 󰗊
    "typ"              => Icons::TYPST           , // 
    "unity"            => Icons::UNITY           , // 
    "unity3d"          => Icons::UNITY           , // 
    "eps"              => Icons::VECTOR          , // 󰕙
    "ps"               => Icons::VECTOR          , // 󰕙
    "svg"              => Icons::VECTOR          , // 󰕙
    "3g2"              => Icons::VIDEO           , // 
    "3gp"              => Icons::VIDEO           , // 
    "3gp2"             => Icons::VIDEO           , // 
    "3gpp"             => Icons::VIDEO           , // 
    "3gpp2"            => Icons::VIDEO           , // 
    "avi"              => Icons::VIDEO           , // 
    "cast"             => Icons::VIDEO           , // 
    "flv"              => Icons::VIDEO           , // 
    "h264"             => Icons::VIDEO           , // 
    "heics"            => Icons::VIDEO           , // 
    "m2ts"             => Icons::VIDEO           , // 
    "m2v"              => Icons::VIDEO           , // 
    "m4v"              => Icons::VIDEO           , // 
    "mkv"              => Icons::VIDEO           , // 
    "mov"              => Icons::VIDEO           , // 
    "mp4"              => Icons::VIDEO           , // 
    "mpeg"             => Icons::VIDEO           , // 
    "mpg"              => Icons::VIDEO           , // 
    "ogm"              => Icons::VIDEO           , // 
    "ogv"              => Icons::VIDEO           , // 
    "video"            => Icons::VIDEO           , // 
    "vob"              => Icons::VIDEO           , // 
    "webm"             => Icons::VIDEO           , // 
    "wmv"              => Icons::VIDEO           , // 
    "vim"              => Icons::VIM             , // 
    "opml"             => Icons::XML             , // 󰗀
    "xml"              => Icons::XML             , // 󰗀
    "xul"              => Icons::XML             , // 󰗀
    "yaml"             => Icons::YAML            , // 
    "yml"              => Icons::YAML            , // 
};

/* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— */

/// Converts the style used to paint a file name into the style that should be
/// used to paint an icon.
///
/// - The background colour should be preferred to the foreground colour, as
///   if one is set, it’s the more “obvious” colour choice.
/// - If neither is set, just use the default style.
/// - Attributes such as bold or underline should not be used to paint the
///   icon, as they can make it look weird.
pub fn iconify_style(style: Style) -> Style {
    style
        .background
        .or(style.foreground)
        .map(Style::from)
        .unwrap_or_default()
}

/// Lookup the icon for a plain file name and lowercase extension, without
/// needing a whole `File`. Used by the `--code` summary to give each
/// language the icon of a representative source file.
pub fn icon_for_name_ext(name: &str, ext: Option<&str>) -> char {
    if let Some(icon) = FILENAME_ICONS.get(name) {
        *icon
    } else if let Some(ext) = ext {
        *EXTENSION_ICONS.get(ext).unwrap_or(&Icons::FILE) //
    } else {
        Icons::FILE_UNKNOW // 󰡯
    }
}

/// Lookup the icon for a file based on the file's name, if the entry is a
/// directory, or by the lowercase file extension.
pub fn icon_for_file(file: &File<'_>) -> char {
    if file.points_to_directory() {
        *DIRECTORY_ICONS.get(file.name.as_str()).unwrap_or_else(|| {
            if file.is_empty_dir() {
                &Icons::FOLDER_OPEN // 
            } else {
                &Icons::FOLDER // 
            }
        })
    } else if let Some(icon) = FILENAME_ICONS.get(file.name.as_str()) {
        *icon
    } else if let Some(ext) = file.ext.as_ref() {
        *EXTENSION_ICONS.get(ext.as_str()).unwrap_or(&Icons::FILE) // 
    } else {
        Icons::FILE_UNKNOW // 󰡯
    }
}
